version: "3.2"

services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://example:example@db:5432/marketcomparedb

    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: db 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: marketcomparedb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432