version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build: 
    docker: 
      - image: circleci/node:12.18
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: julienke02
          password: $DOCKER_PASSWORD # context / project UI env-var reference
        environment:
          POSTGRES_USER: example
          POSTGRES_DB: marketcomparedb
    steps:
      - checkout

      - run: cd api && npm ci
      - run: cd api && npm test


      - setup_remote_docker
      
      - run: |
          cd api
          TAG="0.1.${CIRCLE_BUILD_NUM}"
          docker build -t julienke02/market-price-compare:$TAG .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker push julienke02/market-price-compare:$TAG